// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: qr.proto

package qr

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Tipos de firma digital soportada por ahora solo ECDSA_P256_SHA256
type SigScheme int32

const (
	SigScheme_ECDSA_P256_SHA256 SigScheme = 0
)

// Enum value maps for SigScheme.
var (
	SigScheme_name = map[int32]string{
		0: "ECDSA_P256_SHA256",
	}
	SigScheme_value = map[string]int32{
		"ECDSA_P256_SHA256": 0,
	}
)

func (x SigScheme) Enum() *SigScheme {
	p := new(SigScheme)
	*p = x
	return p
}

func (x SigScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SigScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_qr_proto_enumTypes[0].Descriptor()
}

func (SigScheme) Type() protoreflect.EnumType {
	return &file_qr_proto_enumTypes[0]
}

func (x SigScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SigScheme.Descriptor instead.
func (SigScheme) EnumDescriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{0}
}

// Tipos de Encriptacion Soportados
type EncScheme int32

const (
	// sin encriptación
	EncScheme_NONE EncScheme = 0
)

// Enum value maps for EncScheme.
var (
	EncScheme_name = map[int32]string{
		0: "NONE",
	}
	EncScheme_value = map[string]int32{
		"NONE": 0,
	}
)

func (x EncScheme) Enum() *EncScheme {
	p := new(EncScheme)
	*p = x
	return p
}

func (x EncScheme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncScheme) Descriptor() protoreflect.EnumDescriptor {
	return file_qr_proto_enumTypes[1].Descriptor()
}

func (EncScheme) Type() protoreflect.EnumType {
	return &file_qr_proto_enumTypes[1]
}

func (x EncScheme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncScheme.Descriptor instead.
func (EncScheme) EnumDescriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{1}
}

// Tipo de mensajes a ser disponibles a ser codificados en el cuerpo
type MessageKind int32

const (
	MessageKind_QRActivatePuestoKind MessageKind = 0
	MessageKind_QRVoucherKind        MessageKind = 1
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "QRActivatePuestoKind",
		1: "QRVoucherKind",
	}
	MessageKind_value = map[string]int32{
		"QRActivatePuestoKind": 0,
		"QRVoucherKind":        1,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_qr_proto_enumTypes[2].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_qr_proto_enumTypes[2]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{2}
}

// Cada mensaje seguro es de este tipo y tiene un encabezado y cuerpo y firma digital
type SecureMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// header_and_body es un array de bytes y debe contener un mensaje de tipo HeaderAndBody
	HeaderAndBody []byte `protobuf:"bytes,1,opt,name=header_and_body,json=headerAndBody,proto3" json:"header_and_body,omitempty"`
	// firma de header_and_body
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SecureMessage) Reset() {
	*x = SecureMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureMessage) ProtoMessage() {}

func (x *SecureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureMessage.ProtoReflect.Descriptor instead.
func (*SecureMessage) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{0}
}

func (x *SecureMessage) GetHeaderAndBody() []byte {
	if x != nil {
		return x.HeaderAndBody
	}
	return nil
}

func (x *SecureMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HeaderAndBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Datos publicos del mensaje
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Cuerpo del mensaje
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *HeaderAndBody) Reset() {
	*x = HeaderAndBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderAndBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderAndBody) ProtoMessage() {}

func (x *HeaderAndBody) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderAndBody.ProtoReflect.Descriptor instead.
func (*HeaderAndBody) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderAndBody) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HeaderAndBody) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignatureScheme  SigScheme   `protobuf:"varint,1,opt,name=signature_scheme,json=signatureScheme,proto3,enum=qr.SigScheme" json:"signature_scheme,omitempty"`
	EncryptionScheme EncScheme   `protobuf:"varint,2,opt,name=encryption_scheme,json=encryptionScheme,proto3,enum=qr.EncScheme" json:"encryption_scheme,omitempty"`
	MessageKind      MessageKind `protobuf:"varint,3,opt,name=message_kind,json=messageKind,proto3,enum=qr.MessageKind" json:"message_kind,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetSignatureScheme() SigScheme {
	if x != nil {
		return x.SignatureScheme
	}
	return SigScheme_ECDSA_P256_SHA256
}

func (x *Header) GetEncryptionScheme() EncScheme {
	if x != nil {
		return x.EncryptionScheme
	}
	return EncScheme_NONE
}

func (x *Header) GetMessageKind() MessageKind {
	if x != nil {
		return x.MessageKind
	}
	return MessageKind_QRActivatePuestoKind
}

// QR codificado para activar un puesto
type QRActivatePuesto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// nombre de la empresa
	EmpresaNombre string `protobuf:"bytes,1,opt,name=empresa_nombre,json=empresaNombre,proto3" json:"empresa_nombre,omitempty"`
	// identificador de empresa
	EmpresaId uint32 `protobuf:"varint,2,opt,name=empresa_id,json=empresaId,proto3" json:"empresa_id,omitempty"`
	// identificador de puesto
	PuestoId uint32 `protobuf:"varint,3,opt,name=puesto_id,json=puestoId,proto3" json:"puesto_id,omitempty"`
	// array de identificadores recorridos validos cargados en el sistema
	Recorridos []uint32 `protobuf:"varint,4,rep,packed,name=recorridos,proto3" json:"recorridos,omitempty"`
	// url utilizada para rendir los vouchers
	UrlApi string `protobuf:"bytes,5,opt,name=url_api,json=urlApi,proto3" json:"url_api,omitempty"`
	// token de autorización que debe ser utilizado en url_api para autenticacion
	Token string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *QRActivatePuesto) Reset() {
	*x = QRActivatePuesto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRActivatePuesto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRActivatePuesto) ProtoMessage() {}

func (x *QRActivatePuesto) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRActivatePuesto.ProtoReflect.Descriptor instead.
func (*QRActivatePuesto) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{3}
}

func (x *QRActivatePuesto) GetEmpresaNombre() string {
	if x != nil {
		return x.EmpresaNombre
	}
	return ""
}

func (x *QRActivatePuesto) GetEmpresaId() uint32 {
	if x != nil {
		return x.EmpresaId
	}
	return 0
}

func (x *QRActivatePuesto) GetPuestoId() uint32 {
	if x != nil {
		return x.PuestoId
	}
	return 0
}

func (x *QRActivatePuesto) GetRecorridos() []uint32 {
	if x != nil {
		return x.Recorridos
	}
	return nil
}

func (x *QRActivatePuesto) GetUrlApi() string {
	if x != nil {
		return x.UrlApi
	}
	return ""
}

func (x *QRActivatePuesto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type QRVoucher struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// identificador de voucher
	VoucherId uint32 `protobuf:"varint,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	// tipo de voucher
	TipoVoucher uint32 `protobuf:"varint,2,opt,name=tipo_voucher,json=tipoVoucher,proto3" json:"tipo_voucher,omitempty"`
	// tipo de beneficiario
	TipoBeneficio uint32 `protobuf:"varint,3,opt,name=tipo_beneficio,json=tipoBeneficio,proto3" json:"tipo_beneficio,omitempty"`
	// fecha de viaje
	Fecha *Date `protobuf:"bytes,4,opt,name=fecha,proto3" json:"fecha,omitempty"`
	// identificador de empresa
	EmpresaId uint32 `protobuf:"varint,5,opt,name=empresa_id,json=empresaId,proto3" json:"empresa_id,omitempty"`
	// identificador de recorrido
	Recorrido uint32 `protobuf:"varint,6,opt,name=recorrido,proto3" json:"recorrido,omitempty"`
	// número de documento de beneficiario
	Documento uint32 `protobuf:"varint,7,opt,name=documento,proto3" json:"documento,omitempty"`
	// apellido y nombre beneficiario
	Nombre string `protobuf:"bytes,8,opt,name=nombre,proto3" json:"nombre,omitempty"`
	// localidad de origen y destino
	DesdeHasta string `protobuf:"bytes,9,opt,name=desde_hasta,json=desdeHasta,proto3" json:"desde_hasta,omitempty"`
}

func (x *QRVoucher) Reset() {
	*x = QRVoucher{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRVoucher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRVoucher) ProtoMessage() {}

func (x *QRVoucher) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRVoucher.ProtoReflect.Descriptor instead.
func (*QRVoucher) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{4}
}

func (x *QRVoucher) GetVoucherId() uint32 {
	if x != nil {
		return x.VoucherId
	}
	return 0
}

func (x *QRVoucher) GetTipoVoucher() uint32 {
	if x != nil {
		return x.TipoVoucher
	}
	return 0
}

func (x *QRVoucher) GetTipoBeneficio() uint32 {
	if x != nil {
		return x.TipoBeneficio
	}
	return 0
}

func (x *QRVoucher) GetFecha() *Date {
	if x != nil {
		return x.Fecha
	}
	return nil
}

func (x *QRVoucher) GetEmpresaId() uint32 {
	if x != nil {
		return x.EmpresaId
	}
	return 0
}

func (x *QRVoucher) GetRecorrido() uint32 {
	if x != nil {
		return x.Recorrido
	}
	return 0
}

func (x *QRVoucher) GetDocumento() uint32 {
	if x != nil {
		return x.Documento
	}
	return 0
}

func (x *QRVoucher) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *QRVoucher) GetDesdeHasta() string {
	if x != nil {
		return x.DesdeHasta
	}
	return ""
}

type Date struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Año
	Year int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	// Mes del año de 1 a 12
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	// Dia del mes de 1 a 31
	Day int32 `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *Date) Reset() {
	*x = Date{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_qr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_qr_proto_rawDescGZIP(), []int{5}
}

func (x *Date) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Date) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *Date) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

var File_qr_proto protoreflect.FileDescriptor

var file_qr_proto_rawDesc = []byte{
	0x0a, 0x08, 0x71, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x71, 0x72, 0x22, 0x55,
	0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x41, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x47, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41,
	0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x22, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x71, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xb2,
	0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x10, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x71, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x65, 0x52, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x71, 0x72, 0x2e, 0x45, 0x6e, 0x63, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x52, 0x10, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12,
	0x32, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x71, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x22, 0xc4, 0x01, 0x0a, 0x10, 0x51, 0x52, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x50, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x61, 0x5f, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x72, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x72, 0x69, 0x64, 0x6f, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x72, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x72,
	0x6c, 0x41, 0x70, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xa8, 0x02, 0x0a, 0x09, 0x51,
	0x52, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x6f, 0x75, 0x63,
	0x68, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x6f,
	0x75, 0x63, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x70, 0x6f, 0x5f,
	0x76, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74,
	0x69, 0x70, 0x6f, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69,
	0x70, 0x6f, 0x5f, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x74, 0x69, 0x70, 0x6f, 0x42, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69,
	0x6f, 0x12, 0x1e, 0x0a, 0x05, 0x66, 0x65, 0x63, 0x68, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x71, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x05, 0x66, 0x65, 0x63, 0x68,
	0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x72, 0x69, 0x64, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x72, 0x69, 0x64, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x64, 0x65, 0x5f, 0x68, 0x61,
	0x73, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x64, 0x65,
	0x48, 0x61, 0x73, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x2a, 0x22, 0x0a, 0x09, 0x53, 0x69, 0x67,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x43, 0x44, 0x53, 0x41, 0x5f,
	0x50, 0x32, 0x35, 0x36, 0x5f, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x10, 0x00, 0x2a, 0x15, 0x0a,
	0x09, 0x45, 0x6e, 0x63, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x2a, 0x3a, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b,
	0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x14, 0x51, 0x52, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x50, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x4b, 0x69, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x51, 0x52, 0x56, 0x6f, 0x75, 0x63, 0x68, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x64, 0x10, 0x01,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x71, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qr_proto_rawDescOnce sync.Once
	file_qr_proto_rawDescData = file_qr_proto_rawDesc
)

func file_qr_proto_rawDescGZIP() []byte {
	file_qr_proto_rawDescOnce.Do(func() {
		file_qr_proto_rawDescData = protoimpl.X.CompressGZIP(file_qr_proto_rawDescData)
	})
	return file_qr_proto_rawDescData
}

var file_qr_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_qr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_qr_proto_goTypes = []interface{}{
	(SigScheme)(0),           // 0: qr.SigScheme
	(EncScheme)(0),           // 1: qr.EncScheme
	(MessageKind)(0),         // 2: qr.MessageKind
	(*SecureMessage)(nil),    // 3: qr.SecureMessage
	(*HeaderAndBody)(nil),    // 4: qr.HeaderAndBody
	(*Header)(nil),           // 5: qr.Header
	(*QRActivatePuesto)(nil), // 6: qr.QRActivatePuesto
	(*QRVoucher)(nil),        // 7: qr.QRVoucher
	(*Date)(nil),             // 8: qr.Date
}
var file_qr_proto_depIdxs = []int32{
	5, // 0: qr.HeaderAndBody.header:type_name -> qr.Header
	0, // 1: qr.Header.signature_scheme:type_name -> qr.SigScheme
	1, // 2: qr.Header.encryption_scheme:type_name -> qr.EncScheme
	2, // 3: qr.Header.message_kind:type_name -> qr.MessageKind
	8, // 4: qr.QRVoucher.fecha:type_name -> qr.Date
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_qr_proto_init() }
func file_qr_proto_init() {
	if File_qr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecureMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderAndBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRActivatePuesto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QRVoucher); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Date); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qr_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qr_proto_goTypes,
		DependencyIndexes: file_qr_proto_depIdxs,
		EnumInfos:         file_qr_proto_enumTypes,
		MessageInfos:      file_qr_proto_msgTypes,
	}.Build()
	File_qr_proto = out.File
	file_qr_proto_rawDesc = nil
	file_qr_proto_goTypes = nil
	file_qr_proto_depIdxs = nil
}
